#!/bin/bash

# Workaround for Markdown render target filename flexibility
# and RRDTool Python dump support.

#
# Settings
#
# Used to run analyze script
analyze="python analyze.py"
# Path to upload config.
uploadConfig="upload.config"

#
# Script
#

# Change to directory the script is stored in.
cd $(dirname "$0")

# Update RRD plots and database, peer count, link length, bulk reject percentage, and Markdown render.
$analyze -q --rrd --peer-count --link-lengths --uptime --bulk-reject --markdown index.md || exit 1

# Move index render to index.html.
mv output/index.md.html output/index.html || exit 2

# Dump RRD database to XML.
# Official Python RRDTool bindings do not expose this.
rrdtool dump size.rrd output/size.xml || exit 3

# Insert site, including RRD dump.
$analyze -q --upload "$uploadConfig" || exit 4

